name = "red-letters"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Cloudflare D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "animation-studio-db"
database_id = "eeccad39-064f-41a0-9b8f-387d4ee7f73f"

# Cloudflare R2 Storage binding for Storyboard assets and audio takes
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "animation-assets"
